---
abstract: 'Run (test) tests from within tests to test if they suceed or fail'
author:
  - 'Ryan Niebur <ryanryan52@gmail.com>'
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3601'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-TestHarness
provides:
  Test::TestHarness:
    file: lib/Test/TestHarness.pm
    version: 0.01
requires:
  TAP::Harness: 0
  TAP::Parser::Aggregator: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
